import { createFileRoute } from "@tanstack/react-router";
import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { CodeOutput } from "#/components/code-output";
import { ToolPageLayout } from "#/components/tool-page-layout";
import { Button } from "#/components/ui/button";
import { Card, CardContent } from "#/components/ui/card";
import { Input } from "#/components/ui/input";
import { Label } from "#/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "#/components/ui/select";

export const Route = createFileRoute("/generators/robots-txt")({
	component: RobotsTxtBuilder,
	head: () => ({
		meta: [
			{ title: "robots.txt Builder | WebToolkit" },
			{
				name: "description",
				content: "Build robots.txt with visual controls and presets",
			},
		],
	}),
});

interface PathRule {
	id: string;
	type: "allow" | "disallow";
	path: string;
}

interface RuleGroup {
	id: string;
	userAgent: string;
	crawlDelay: string;
	rules: PathRule[];
}

function RobotsTxtBuilder() {
	const [sitemap, setSitemap] = useState("");
	const [groups, setGroups] = useState<RuleGroup[]>([
		{
			id: "default-group",
			userAgent: "*",
			crawlDelay: "",
			rules: [
				{
					id: "default-rule-1",
					type: "disallow",
					path: "/admin",
				},
				{
					id: "default-rule-2",
					type: "allow",
					path: "/",
				},
			],
		},
	]);

	const addGroup = () => {
		const newId = `group-${Date.now()}`;
		setGroups((prev) => [
			...prev,
			{
				id: newId,
				userAgent: "",
				crawlDelay: "",
				rules: [{ id: `rule-${Date.now()}-1`, type: "disallow", path: "/" }],
			},
		]);
	};

	const removeGroup = (groupId: string) => {
		setGroups((prev) => prev.filter((g) => g.id !== groupId));
	};

	const updateGroupUserAgent = (groupId: string, userAgent: string) => {
		setGroups((prev) =>
			prev.map((g) => (g.id === groupId ? { ...g, userAgent } : g)),
		);
	};

	const updateGroupCrawlDelay = (groupId: string, crawlDelay: string) => {
		setGroups((prev) =>
			prev.map((g) => (g.id === groupId ? { ...g, crawlDelay } : g)),
		);
	};

	const addRule = (groupId: string) => {
		setGroups((prev) =>
			prev.map((g) => {
				if (g.id !== groupId) return g;
				return {
					...g,
					rules: [
						...g.rules,
						{ id: `rule-${Date.now()}`, type: "disallow", path: "/" },
					],
				};
			}),
		);
	};

	const removeRule = (groupId: string, ruleId: string) => {
		setGroups((prev) =>
			prev.map((g) => {
				if (g.id !== groupId) return g;
				return {
					...g,
					rules: g.rules.filter((r) => r.id !== ruleId),
				};
			}),
		);
	};

	const updateRule = (
		groupId: string,
		ruleId: string,
		field: "type" | "path",
		value: string,
	) => {
		setGroups((prev) =>
			prev.map((g) => {
				if (g.id !== groupId) return g;
				return {
					...g,
					rules: g.rules.map((r) => {
						if (r.id !== ruleId) return r;
						return { ...r, [field]: value };
					}),
				};
			}),
		);
	};

	// Presets
	const applyPreset = (preset: "allow-all" | "block-all" | "block-ai") => {
		if (preset === "allow-all") {
			setGroups([
				{
					id: "allow-all",
					userAgent: "*",
					crawlDelay: "",
					rules: [{ id: "allow-all-r1", type: "allow", path: "/" }],
				},
			]);
		} else if (preset === "block-all") {
			setGroups([
				{
					id: "block-all",
					userAgent: "*",
					crawlDelay: "",
					rules: [{ id: "block-all-r1", type: "disallow", path: "/" }],
				},
			]);
		} else if (preset === "block-ai") {
			const crawlers = [
				"GPTBot",
				"ChatGPT-User",
				"Google-Extended",
				"CCBot",
				"anthropic-ai",
			];
			const newGroups = crawlers.map((crawler, index) => ({
				id: `ai-${index}`,
				userAgent: crawler,
				crawlDelay: "",
				rules: [{ id: `ai-r-${index}`, type: "disallow", path: "/" }],
			}));
			// Add a default user agent star rule to allow others
			newGroups.push({
				id: "ai-star",
				userAgent: "*",
				crawlDelay: "",
				rules: [{ id: "ai-star-r", type: "allow", path: "/" }],
			});
			setGroups(newGroups);
		}
	};

	const generateRobotsTxt = () => {
		const lines: string[] = [];

		lines.push("# Generated by WebToolkit robots.txt Builder");
		lines.push("");

		for (const group of groups) {
			const ua = group.userAgent.trim() || "*";
			lines.push(`User-agent: ${ua}`);

			if (group.crawlDelay) {
				const delay = Number.parseInt(group.crawlDelay, 10);
				if (!Number.isNaN(delay) && delay > 0) {
					lines.push(`Crawl-delay: ${delay}`);
				}
			}

			for (const rule of group.rules) {
				const path = rule.path.trim() || "/";
				if (rule.type === "allow") {
					lines.push(`Allow: ${path}`);
				} else {
					lines.push(`Disallow: ${path}`);
				}
			}
			lines.push("");
		}

		if (sitemap.trim()) {
			lines.push(`Sitemap: ${sitemap.trim()}`);
		}

		return lines.join("\n");
	};

	const robotsTxtOutput = generateRobotsTxt();

	return (
		<ToolPageLayout>
			<div className="grid lg:grid-cols-[1fr_450px] gap-8">
				{/* Visual Rule Editor */}
				<div className="space-y-6">
					<div className="flex flex-wrap items-center justify-between gap-4">
						<div className="space-x-2">
							<Button
								variant="outline"
								size="sm"
								onClick={() => applyPreset("allow-all")}
							>
								Allow All
							</Button>
							<Button
								variant="outline"
								size="sm"
								onClick={() => applyPreset("block-all")}
							>
								Block All
							</Button>
							<Button
								variant="outline"
								size="sm"
								onClick={() => applyPreset("block-ai")}
							>
								Block AI Crawlers
							</Button>
						</div>
						<Button size="sm" onClick={addGroup}>
							<Plus className="size-4 mr-2" /> Add Rule Group
						</Button>
					</div>

					<div className="space-y-4">
						{groups.map((group) => (
							<Card key={group.id} className="relative overflow-hidden bg-card">
								<CardContent className="p-5 space-y-4">
									<div className="flex flex-wrap items-end justify-between gap-4 border-b border-border/50 pb-3">
										<div className="flex-1 min-w-[200px] space-y-2">
											<Label htmlFor={`ua-${group.id}`}>User-agent</Label>
											<Input
												id={`ua-${group.id}`}
												value={group.userAgent}
												onChange={(e) =>
													updateGroupUserAgent(group.id, e.target.value)
												}
												placeholder="e.g. *, Googlebot, Bingbot"
											/>
										</div>
										<div className="w-[120px] space-y-2">
											<Label htmlFor={`delay-${group.id}`}>
												Crawl-delay (s)
											</Label>
											<Input
												id={`delay-${group.id}`}
												type="number"
												min="0"
												value={group.crawlDelay}
												onChange={(e) =>
													updateGroupCrawlDelay(group.id, e.target.value)
												}
												placeholder="e.g. 5"
											/>
										</div>
										{groups.length > 1 && (
											<Button
												variant="ghost"
												size="icon"
												className="text-destructive hover:text-destructive hover:bg-destructive/10"
												onClick={() => removeGroup(group.id)}
											>
												<Trash2 className="size-4" />
											</Button>
										)}
									</div>

									<div className="space-y-2">
										<Label>Rules</Label>
										{group.rules.map((rule) => (
											<div
												key={rule.id}
												className="flex items-center gap-2 bg-muted/30 p-1.5 rounded-lg border border-border/30"
											>
												<Select
													value={rule.type}
													onValueChange={(val: "allow" | "disallow") =>
														updateRule(group.id, rule.id, "type", val)
													}
												>
													<SelectTrigger className="w-[120px] bg-background">
														<SelectValue />
													</SelectTrigger>
													<SelectContent>
														<SelectItem value="allow">Allow</SelectItem>
														<SelectItem value="disallow">Disallow</SelectItem>
													</SelectContent>
												</Select>
												<Input
													value={rule.path}
													onChange={(e) =>
														updateRule(
															group.id,
															rule.id,
															"path",
															e.target.value,
														)
													}
													placeholder="e.g. /"
													className="flex-1 bg-background"
												/>
												{group.rules.length > 1 && (
													<Button
														variant="ghost"
														size="icon"
														className="text-muted-foreground hover:text-destructive"
														onClick={() => removeRule(group.id, rule.id)}
													>
														<Trash2 className="size-4" />
													</Button>
												)}
											</div>
										))}
									</div>

									<Button
										variant="ghost"
										size="sm"
										className="w-full border border-dashed border-border/60 hover:bg-muted"
										onClick={() => addRule(group.id)}
									>
										<Plus className="size-3.5 mr-1.5" /> Add Path Rule
									</Button>
								</CardContent>
							</Card>
						))}
					</div>

					<div className="bg-card border border-border rounded-xl p-5 space-y-4">
						<h3 className="font-semibold text-sm">Global Settings</h3>
						<div className="space-y-2">
							<Label htmlFor="sitemap-url">Sitemap URL</Label>
							<Input
								id="sitemap-url"
								value={sitemap}
								onChange={(e) => setSitemap(e.target.value)}
								placeholder="e.g. https://example.com/sitemap.xml"
							/>
						</div>
					</div>
				</div>

				{/* Output Panel */}
				<div className="flex flex-col space-y-4">
					<h3 className="font-semibold text-lg">Generated robots.txt</h3>
					<div className="flex-1">
						<CodeOutput
							code={robotsTxtOutput}
							language="text"
							label="robots.txt content"
						/>
					</div>
				</div>
			</div>
		</ToolPageLayout>
	);
}
